export const daySchedule = {
  Monday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Monday",
  },
  Tuesday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Tuesday",
  },
  Wednesday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Wednesday",
  },
  Thursday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Thursday",
  },
  Friday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Friday",
  },
  Saturday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Saturday",
  },
  Sunday: {
    school: "",
    class_assigned: "",
    subject: "",
    teacher: "",
    start_time: "",
    end_time: "",
    day: "Sunday",
  },
};
