export const columnHeaders = [
  "2025-05-07",
  "2025-05-08",
  "2025-05-09",
  "2025-05-10",
  "2025-05-11",
  "2025-05-12",
];

export const rowHeaders = [
  "9am to 10am",
  "10am to 11am",
  "11am to 12pm",
  "12pm to 1pm",
];

export const dummyText =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";

export const tableData = [
  {
    time: "9am to 10am",
    records: [
      {
        date: "2025-05-07",
        punchInTime: "9:05am",
        punchOutTime: "9:55am",
        late: "5 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-08",
        punchInTime: "9:10am",
        punchOutTime: "10:00am",
        late: "10 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-09",
        punchInTime: "9:05am",
        punchOutTime: "9:55am",
        late: "5 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-10",
        punchInTime: "9:10am",
        punchOutTime: "10:00am",
        late: "10 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-11",
        punchInTime: "9:05am",
        punchOutTime: "9:55am",
        late: "5 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-12",
        punchInTime: "9:10am",
        punchOutTime: "10:00am",
        late: "10 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
    ],
  },
  {
    time: "10am to 11am",
    records: [
      {
        date: "2025-05-07",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
      },
      {
        date: "2025-05-08",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
      },
      {
        date: "2025-05-09",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
      },
      {
        date: "2025-05-10",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
      },
      {
        date: "2025-05-11",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
      },
      {
        date: "2025-05-12",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
      },
    ],
  },
  {
    time: "11am to 12pm",
    records: [
      {
        date: "2025-05-07",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-08",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-09",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-10",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-11",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-12",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
    ],
  },
  {
    time: "12pm to 1pm",
    records: [
      {
        date: "2025-05-07",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-08",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-09",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-10",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-11",
        punchInTime: "10:00am",
        punchOutTime: "11:00am",
        late: "0 mins",
        early: "0 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
      {
        date: "2025-05-12",
        punchInTime: "10:15am",
        punchOutTime: "11:05am",
        late: "15 mins",
        early: "5 mins",
        punchInPhoto: "",
        punchOutPhoto: "",
        punchInReason: dummyText,
        punchOutReason: dummyText,
      },
    ],
  },
];

export const filterTypes = [
  { label: "Today", value: "Today" },
  { label: "Week", value: "Week" },
  { label: "Month", value: "Month" },
  { label: "Custom", value: "Custom" },
];
